services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rssagg
    volumes:
      - rssagg_pg_data:/bitnami/postgresql
  sqlc:
    image: sqlc/sqlc
    working_dir: /src
    volumes:
      - ./:/src

volumes:
  rssagg_pg_data:
